# -*- coding: utf-8 -*-
"""EDA_Notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/ashish4129/eda-notebook.152c8799-7fc1-4e73-90ef-198b42de26cb.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251129/auto/storage/goog4_request%26X-Goog-Date%3D20251129T030159Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D30256623d9d47f2898b4965f5c85d284ffaa57ca39a78b691f4c62cad67cfa051a1f41a42372c6a36bd192b69ccf0ed75657793bd54fc7b6d1cda06aad579f5704f6d3a703cad52c49cc45098ee729ce83cd15e7ee2009748f8126a60fc927c4196bf82dc2a69785ed42765318b529df7c1c3f9e3d31666a7a77fa374ad3cb0b691739f7c1f8c7c586435a2ba6b8e4d93f85aa25a3c512f1ee32c5cb6f0fac15f618848a8153af6bd09fd6bf5459ff60f263e25052dbcf82ebf5b122dc647586b8f8a0afe57eb3b241a53c29eccd13b0e51cc226b6216ee99e6d1f396d0539b36d81d3c56462831a596ebdb6244fb7c6a1bc0a5c47426b226ab8bb75be6022dd
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("default")
sns.set_theme()

train_path = "/kaggle/input/2025-sep-dl-gen-ai-project/train.csv"

df = pd.read_csv(train_path)
print("Shape:", df.shape)
df.head()

print("Columns:", df.columns.tolist())
print("\nData Types:\n")
print(df.dtypes)

print("\nNull values per column:\n")
print(df.isnull().sum())

# Emotion label columns
label_cols = ["anger", "fear", "joy", "sadness", "surprise"]

print("Label columns:", label_cols)

# Ensure they are int (0/1)
for col in label_cols:
    df[col] = df[col].astype(int)

print("\nTotal positives per label:")
print(df[label_cols].sum())

# Number of labels per sample
df["num_labels"] = df[label_cols].sum(axis=1)

print("\nDistribution of number of labels per sample:")
print(df["num_labels"].value_counts().sort_index())

fig, ax = plt.subplots(figsize=(6, 4))
label_counts = df[label_cols].sum().sort_values(ascending=False)

sns.barplot(x=label_counts.index, y=label_counts.values, ax=ax)
ax.set_title("Label Frequency (Number of Positive Samples per Emotion)")
ax.set_ylabel("Count")
ax.set_xlabel("Emotion")
plt.show()

df["text_len_words"] = df["text"].fillna("").apply(lambda x: len(str(x).split()))
df["text_len_chars"] = df["text"].fillna("").apply(lambda x: len(str(x)))

print("Word length stats:\n", df["text_len_words"].describe())
print("\nChar length stats:\n", df["text_len_chars"].describe())

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

sns.histplot(df["text_len_words"], bins=40, kde=False, ax=axes[0])
axes[0].set_title("Distribution of Text Length (Words)")
axes[0].set_xlabel("Number of words")

sns.histplot(df["text_len_chars"], bins=40, kde=False, ax=axes[1])
axes[1].set_title("Distribution of Text Length (Characters)")
axes[1].set_xlabel("Number of characters")

plt.tight_layout()
plt.show()

# Show some examples with multiple label
multi_label_samples = df[df["num_labels"] > 1].head(10)

print("Examples with multiple emotions\n\n")
for i, row in multi_label_samples.iterrows():
    labels_present = [lab for lab in label_cols if row[lab] == 1]
    print(f"Text: {row['text']}")
    print(f"Labels: {labels_present}")
    print("-" * 80)

co_matrix = np.zeros((len(label_cols), len(label_cols)), dtype=int)

for _, row in df[label_cols].iterrows():
    active = np.where(row.values == 1)[0]
    for i in active:
        for j in active:
            if i != j:
                co_matrix[i, j] += 1

co_df = pd.DataFrame(co_matrix, index=label_cols, columns=label_cols)

plt.figure(figsize=(6, 5))
sns.heatmap(co_df, annot=True, fmt="d", cmap="Blues")
plt.title("Label Co-occurrence Matrix")
plt.show()